name: viz
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - numpy
  - pandas
  - matplotlib
  - colorcet
  - seaborn
  - opencv=3.4.2
  - ipython
  - jupyter
  - pip
  - panel=0.11.3
  - holoviews=1.14.5
  - plotly
  - python-kaleido
  - hvplot
  - pip:
    - wavio
    - moviepy
